services:
  naruto-chronicles:
    build:
      context: .
      args:
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
        - NEXT_PUBLIC_UMAMI_WEBSITE_ID=${NEXT_PUBLIC_UMAMI_WEBSITE_ID}
        - NEXT_PUBLIC_UMAMI_URL=${NEXT_PUBLIC_UMAMI_URL}
        - DATABASE_URL=${DATABASE_URL}
    image: naruto:latest
    container_name: naruto-chronicles
    restart: always
    ports:
      - 127.0.0.1:3001:3001
    env_file:
      - .env
    volumes:
      - ./prisma:/app/prisma
